# templates/rolebinding/api-gateway-rb.yaml
{{- if index .Values "api-gateway" "enabled" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-reader-binding
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ecommerce-app.fullname" . }}-api-gateway-sa
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: api-gateway-service-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}