apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: monitoring
  labels:
    release: monitoring  
spec:
  selector:
    matchLabels:
      app: api-gateway
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}    
  endpoints:
    - port: http                     
      path: /actuator/prometheus
      interval: 15s
