apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-service
  namespace: monitoring
  labels:
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: payment-service
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}    
  endpoints:
    - port: http                     
      path: /payment-service/actuator/prometheus
      interval: 15s
