{{- if (index .Values "service-discovery" "hpa" "enabled") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-discovery-hpa
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-discovery
  minReplicas: {{ index .Values "service-discovery" "hpa" "minReplicas" }}
  maxReplicas: {{ index .Values "service-discovery" "hpa" "maxReplicas" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ index .Values "service-discovery" "hpa" "targetCPUUtilizationPercentage" }}
{{- end }}
