apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: {{ index .Values "user-service" "hpa" "minReplicas" }}
  maxReplicas: {{ index .Values "user-service" "hpa" "maxReplicas" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ index .Values "user-service" "hpa" "cpuUtilization" }}