{{- if or (eq .Values.global.namespace "stage") (eq .Values.global.namespace "prod") -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage
  namespace: {{ .Values.global.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
{{- end }}