apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: {{ index .Values "api-gateway" "service" "port" }}
    targetPort: {{ index .Values "api-gateway" "service" "port" }}
    protocol: TCP
  type: {{ index .Values "api-gateway" "service" "type" }}
