apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  # PostgreSQL credentials (base64 encoded)
  # Default values for dev environment
  # user: ecommerce_user
  DB_USERNAME: {{ .Values.secrets.database.username | b64enc | quote }}
  # password: ecommerce_pass123
  DB_PASSWORD: {{ .Values.secrets.database.password | b64enc | quote }}
  # Database URLs for each service
  USER_DB_URL: {{ printf "jdbc:postgresql://user-db:5432/user_service_db" | b64enc | quote }}
  PRODUCT_DB_URL: {{ printf "jdbc:postgresql://product-db:5432/product_service_db" | b64enc | quote }}
  ORDER_DB_URL: {{ printf "jdbc:postgresql://order-db:5432/order_service_db" | b64enc | quote }}
  PAYMENT_DB_URL: {{ printf "jdbc:postgresql://payment-db:5432/payment_service_db" | b64enc | quote }}
  SHIPPING_DB_URL: {{ printf "jdbc:postgresql://shipping-db:5432/shipping_service_db" | b64enc | quote }}
  FAVOURITE_DB_URL: {{ printf "jdbc:postgresql://favourite-db:5432/favourite_service_db" | b64enc | quote }}
