apiVersion: v1
kind: Secret
metadata:
  name: external-api-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  # Payment gateway API credentials (Stripe/PayPal example)
  # key: sk_test_payment_api_key_123456789
  PAYMENT_API_KEY: {{ .Values.secrets.externalApis.paymentApiKey | b64enc | quote }}
  PAYMENT_API_SECRET: {{ .Values.secrets.externalApis.paymentApiSecret | b64enc | quote }}
  
  # Shipping provider API credentials
  # key: ship_api_key_987654321
  SHIPPING_API_KEY: {{ .Values.secrets.externalApis.shippingApiKey | b64enc | quote }}
  SHIPPING_API_SECRET: {{ .Values.secrets.externalApis.shippingApiSecret | b64enc | quote }}
  
  # Email service credentials (SMTP)
  EMAIL_USERNAME: {{ .Values.secrets.externalApis.emailUsername | b64enc | quote }}
  EMAIL_PASSWORD: {{ .Values.secrets.externalApis.emailPassword | b64enc | quote }}
