apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: {{ index .Values "order-service" "service" "port" }}
    targetPort: {{ index .Values "order-service" "service" "port" }}
    protocol: TCP
  type: {{ index .Values "order-service" "service" "type" }}
