apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-client
spec:
  selector:
    app: proxy-client
  ports:
  - port: {{ index .Values "proxy-client" "service" "port" }}
    targetPort: {{ index .Values "proxy-client" "service" "port" }}
    protocol: TCP
  type: {{ index .Values "proxy-client" "service" "type" }}
