apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
  - port: {{ index .Values "shipping-service" "service" "port" }}
    targetPort: {{ index .Values "shipping-service" "service" "port" }}
    protocol: TCP
  type: {{ index .Values "shipping-service" "service" "type" }}
