{{- if .Values.ingress.enabledTls }}
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-tls
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/tls.key" | b64enc }}
{{- end }}
