apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - name: http
    port: {{ index .Values "user-service" "service" "port" }}
    targetPort: {{ index .Values "user-service" "service" "port" }}
    protocol: TCP
  type: {{ index .Values "user-service" "service" "type" }}
