apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    # Pod Security Standards - Nivel RESTRICTED
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest

