apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{ .Values.global.namespace }}
  labels:
    app: zipkin
spec:
  selector:
    app: zipkin
    color: {{ .Values.blueGreen.activeColor }}
  ports:
  - port: {{ .Values.zipkin.service.port }} 
    targetPort: 9411
    protocol: TCP
  type: {{ .Values.zipkin.service.type }}