# templates/role/api-gateway-role.yaml
{{- if index .Values "api-gateway" "enabled" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-gateway-service-reader
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
rules:
- apiGroups: [""] 
  resources: ["services", "endpoints"] 
  verbs: ["get", "list", "watch"]
{{- end }}