# templates/role/service-discovery-role.yaml
{{- if index .Values "service-discovery" "enabled" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-discovery-watcher
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
rules:
- apiGroups: [""] 
  resources: ["services", "endpoints"] 
  verbs: ["get", "list", "watch"]
{{- end }}